version: '3.3' # specify docker-compose version

# Define the services/containers to be run
services:
  postgresdb:
    image: postgres:12.10-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

    volumes:
      - ./initdb/:/docker-entrypoint-initdb.d/
      - postgres-volume:/var/lib/postgresql/data

    ports:
      - 5432:5432

  postgres-pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=devops@tai.it
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_DEFAULT_SERVER=postgresdb
    volumes:
      - pgadmin-volume:/var/lib/pgadmin

    ports:
      - 5435:80
      
    depends_on:
      - postgresdb
volumes:
  postgres-volume:
  pgadmin-volume: